# Generated by Django 3.0.7 on 2020-07-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contect',
        ),
    ]
