# Generated by Django 3.0.7 on 2020-07-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200708_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contect',
            new_name='Contact',
        ),
    ]
